/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bilca
 */
import dao.ConnectionProvider;
import java.sql.Connection;

import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

public class AddSubs extends javax.swing.JFrame {
 private String username=" ";
    /**
     * Creates new form AddSubs
     */
    public AddSubs() {
        initComponents();
    }public AddSubs(String  tempUsername){
         initComponents();
         username = tempUsername;
         setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yellowPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboSem = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboSubs = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboHours = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        comboDay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboID = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        yellowPanel.setBackground(new java.awt.Color(0, 153, 153));
        yellowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sub No.");
        yellowPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        comboSem.setBackground(new java.awt.Color(255, 255, 255));
        comboSem.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboSem.setForeground(new java.awt.Color(0, 0, 0));
        comboSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                       ", "1st Semester", "2nd Semester" }));
        comboSem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        yellowPanel.add(comboSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 320, 40));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year 1 : Midterm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        yellowPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 220, 40));

        comboSubs.setBackground(new java.awt.Color(255, 255, 255));
        comboSubs.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboSubs.setForeground(new java.awt.Color(0, 0, 0));
        comboSubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "ELEC 1-Multimedia System", "GE AA - Art Appreciation", "GE CW -The Contemporary World", "GEE TEM -The Entrepreneurial Mind", "IT 211-Fundamentals of Database System 1", "IT 212-Computer Programming 2", "IT 214 -Networking 1", "CC 222-Database System 2", "CC 222-Data Structures and Algorithms", "FREE ELEC 1-Graphics, Design and Animation\t\t", "GE STS-Science, Technology and Society\t\t", "IT 223-Information Assurance and Security ", "IT 224-System Analysis and Design\t", "IT 211, IT 212", "PE 4 PATHFit 4: Dance, Sports, Martial Arts, Group Exercise\t", " ", " " }));
        yellowPanel.add(comboSubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 320, 40));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Subjects");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        yellowPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 220, 40));

        comboHours.setBackground(new java.awt.Color(255, 255, 255));
        comboHours.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboHours.setForeground(new java.awt.Color(0, 0, 0));
        comboHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                   ", "9:00 AM - 10:30 AM", "11:00 AM - 12:30 PM", "2:00 PM - 3:30 PM", "8:00 AM - 9:30 AM", "10:00 AM - 11:30 AM", "1:00 PM - 2:30 PM", " " }));
        yellowPanel.add(comboHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 320, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hour Schedule");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        yellowPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, 40));

        comboDay.setBackground(new java.awt.Color(255, 255, 255));
        comboDay.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboDay.setForeground(new java.awt.Color(0, 0, 0));
        comboDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", " " }));
        yellowPanel.add(comboDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 320, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Day Schedule");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        yellowPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 220, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        yellowPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 730, 10));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        yellowPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        yellowPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 80, 40));

        comboID.setBackground(new java.awt.Color(255, 255, 255));
        comboID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comboID.setForeground(new java.awt.Color(0, 0, 0));
        comboID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002  ", "003  ", "004   ", "005", "006", "007", "008" }));
        yellowPanel.add(comboID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 170, 30));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        yellowPanel.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add Subjects");
        yellowPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        yellowPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SRS-removebg-preview (1).png"))); // NOI18N
        yellowPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        yellowPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile/stDb (1) (1).jpg"))); // NOI18N
        yellowPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yellowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(yellowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sem = (String) comboSem.getSelectedItem();
        String user = txtUser.getText();
        String hours = (String) comboHours.getSelectedItem();
        String subs = (String) comboSubs.getSelectedItem();
        String id = (String) comboID.getSelectedItem();
        String days = (String) comboDay.getSelectedItem();

        try {
            // Validate inputs
            if (sem == null || sem.trim().isEmpty() ||
                hours == null || hours.trim().isEmpty() ||
                subs == null || subs.trim().isEmpty() ||
                id == null || id.trim().isEmpty() ||
                    days == null || days.trim().isEmpty()) {
                throw new IllegalArgumentException("All fields must be filled out.");
            }

            // Establish connection to the database
            Connection con = ConnectionProvider.getCon();

            // Prepare SQL query to insert data into the addSubs table
            PreparedStatement ps = con.prepareStatement(
                "INSERT INTO viewSub (username,SubID,Semester, Hours, Subjects,  Days) VALUES (?,?, ?, ?, ?,?)");

            // Bind values to the query
           ps.setString(1, user);
           ps.setString(2, id);
           ps.setString(3, sem);
           ps.setString(4, hours);
           ps.setString(5, subs);
           ps.setString(6, days);

            // Execute the query
            ps.executeUpdate();

            // Success message
            JOptionPane.showMessageDialog(null, "Subject saved successfully!");

            // Navigate to the viewSubs screen or refresh the UI
            setVisible(false); // Hide current frame
            new AddSubs(username).setVisible(true);

        } catch (Exception e) {
            // Handle exceptions
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new StudentDashboard(username).setVisible(true);        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDay;
    private javax.swing.JComboBox<String> comboHours;
    private javax.swing.JComboBox<String> comboID;
    private javax.swing.JComboBox<String> comboSem;
    private javax.swing.JComboBox<String> comboSubs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPanel yellowPanel;
    // End of variables declaration//GEN-END:variables
}
