/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bilca
 */
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;



public class ViewSubs extends javax.swing.JFrame {
 private String username=" ";
   
   
  
   
    /**
     * Creates new form ViewSubs
     */
    public ViewSubs() {
        initComponents();
    } public ViewSubs(String  tempUsername){
         initComponents();
         username = tempUsername;
         setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        green = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        viewSubs = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        subUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        green.setBackground(new java.awt.Color(51, 153, 255));
        green.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                greenComponentShown(evt);
            }
        });
        green.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1202, 430));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 428));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        viewSubs.setBackground(new java.awt.Color(255, 255, 255));
        viewSubs.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        viewSubs.setForeground(new java.awt.Color(0, 0, 0));
        viewSubs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Sub No.", "Semester", "Hour", "Subjects", "Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(viewSubs);
        if (viewSubs.getColumnModel().getColumnCount() > 0) {
            viewSubs.getColumnModel().getColumn(0).setResizable(false);
            viewSubs.getColumnModel().getColumn(0).setPreferredWidth(1);
            viewSubs.getColumnModel().getColumn(1).setResizable(false);
            viewSubs.getColumnModel().getColumn(1).setPreferredWidth(1);
            viewSubs.getColumnModel().getColumn(2).setResizable(false);
            viewSubs.getColumnModel().getColumn(2).setPreferredWidth(1);
            viewSubs.getColumnModel().getColumn(3).setResizable(false);
            viewSubs.getColumnModel().getColumn(4).setResizable(false);
            viewSubs.getColumnModel().getColumn(5).setResizable(false);
            viewSubs.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane4);

        jScrollPane3.setViewportView(jPanel1);

        green.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 640, 430));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        green.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 110, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        green.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 110, -1));
        green.add(subUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SRS-removebg-preview (1).png"))); // NOI18N
        green.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 70));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Subjects");
        green.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile/minor-removebg-preview (1).png"))); // NOI18N
        green.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/local.jpg"))); // NOI18N
        green.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(green, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void greenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_greenComponentShown
         
    }//GEN-LAST:event_greenComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new StudentDashboard(username).setVisible(true); 
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
 DefaultTableModel model =(DefaultTableModel) viewSubs.getModel();
       
       
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from viewSub where username ='"+username+"'");
            while (rs.next()){

                model.addRow(new Object[]{rs.getString("username"),rs.getString("SubID"),rs.getString("Semester"),rs.getString("Hours"),rs.getString("Subjects"),rs.getString("Days")});
              
         
           
                
            
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(StudentDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


      
        
// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int index = viewSubs.getSelectedRow(); // Get the selected row index
        if (index == -1) { 
            JOptionPane.showMessageDialog(null, "Please select a subject to delete.");
            return;
        }

        TableModel model = viewSubs.getModel();
        String id = model.getValueAt(index, 1).toString(); 


        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this Subject?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) { 
            try {
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("DELETE FROM viewSub WHERE SubID = ?");
                ps.setString(1, id); // Bind the ID parameter
                ps.executeUpdate();

                
                JOptionPane.showMessageDialog(null, "Subject Deleted Successfully.");
                ((DefaultTableModel) viewSubs.getModel()).removeRow(index); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "An error occurred while deleting: " + e.getMessage());
            }
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSubs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel subUser;
    private javax.swing.JTable viewSubs;
    // End of variables declaration//GEN-END:variables
}
